### ISSUE TITLE
Campus Map

### ISSUE THREAD

**Issue by gjs1985** [hannonhill/Example-Sites#2]
In order for this to work do I need to have version 7.14.1? I was able to import the site with files. But none of the markers displayed over the map. Not sure. Any suggestions?

**Comment by graham-lewis** [comment]
@gjs1985 Which version of Cascade are you running? Also, can you attach a screenshot of what you see?

**Comment by gjs1985** [comment]
I will have to check on version.  I just know we are a few back, like 7.9....

![campusmapsz](https://cloud.githubusercontent.com/assets/20799123/18925365/567720c6-8579-11e6-9786-149998686efe.jpg)

**Comment by graham-lewis** [comment]
@gjs1985 Try publishing out the "map-files" folder, the icons have to be published out for them to show in the system.

**Comment by gjs1985** [comment]
nope, no luck there.  I tried publishing the 'internal' folder out.  Got an error.  Or is that common when publishing a folder like that out?

**Comment by graham-lewis** [comment]
@gjs1985 what was the error? did you make sure to update the "destination" in the site management area? double check that the files in the "map-files" folder actually published.

![screen shot 2016-09-28 at 12 53 18 pm](https://cloud.githubusercontent.com/assets/12734634/18925718/a2472ae0-857a-11e6-974a-daeffe2f90be.png)

**Comment by gjs1985** [comment]
everything published out in the map-files.  The destination is a development server.  The screenshot i sent was taken from our development site.

The error i got for the 'internal' folder when publishing was: "Asset is not set to publish. Please enable publishing for this asset and try again."

**Comment by graham-lewis** [comment]
One more thing to try - try updating the `siteurl` that is in the categories block to the url that everything is published to

<img width="784" alt="screen shot 2016-09-28 at 1 38 39 pm" src="https://cloud.githubusercontent.com/assets/12734634/18932721/546c3a50-8597-11e6-8f47-b8af6fb5a067.png">

**Comment by graham-lewis** [comment]
@gjs1985 - I tried this on a version I got from the Exchange and adding the Site URL (published url of files) made the icon show up. 

Let me know if this works.

**Comment by gjs1985** [comment]
that worked.  Thank you.

**Comment by graham-lewis** [comment]
great! let me know if you have any other questions, i've been working on an updated look of the map display as well and am more than happy to show that to you as well

**Comment by gjs1985** [comment]
sure, what do you got. I would like to see what others are doing for maps.

**Comment by graham-lewis** [comment]
This is an update/integration option into a page type.
http://publish.cascadeserver.com/training/campus-map/index.html

Also, here is Macomb Community College using the this Campus Map as well.
http://www.macomb.edu/about-macomb/maps-directions/center-campus.html

**Comment by gjs1985** [comment]
I like those.  i'm wondering could the google map use the new 3D layout?

**Comment by graham-lewis** [comment]
I'm sure that it could, probably could added to the options in the editor.

**Comment by graham-lewis** [comment]
@gjs1985 I am going to close this issue for now, if you run into anything else, feel free to reopen it
