### ISSUE TITLE
Site Wide Change?

### ISSUE THREAD

**Issue by gjs1985** [hannonhill/Example-Sites#3]
Can Web Services or an other tool make site/s wide change?  We are working making all our sites compliant with SSL standards.  A number of users used the 'external link' tool/option in cascade. and the links were setup with 'http' any way to use web services to change it to 'https'?

**Comment by rgriffith** [comment]
Hi @gjs1985, your question would be better suited for our [Community forum](https://help.hannonhill.com/hc/en-us/community/topics) as opposed to this example sites repository. Specifically, I would suggest posting your question to either the [How do I...](https://help.hannonhill.com/hc/en-us/community/topics/200829427-How-Do-I-) or the [Web Service](https://help.hannonhill.com/hc/en-us/community/topics/200831028-Web-Services) topic.
